### ISSUE TITLE
[minor bug] Content Update Required

### ISSUE THREAD

**Issue by devxoshakya** [ads-labs/presence#11]
@akshitasrivastava20 - You need to re write these two paragraphs and remove the branding from then, also add our project name in the place of it 

![image](https://github.com/user-attachments/assets/e1a1792a-448a-48e5-942c-0e2991558422)
![image](https://github.com/user-attachments/assets/903ee854-899c-40ab-abe6-425607d6d1bf)

**Comment by akshitasrivastava20** [comment]
#19
